### ISSUE TITLE
Available Kingdoms with no assigned regions

### ISSUE THREAD

**Issue by Enoc-GitHub** [jeffreypicard/medieval-europe#15]
When creating a character, one can choose from many Kingdoms, but some of those Kingdoms have no assigned regions.

![availableKingdoms](https://user-images.githubusercontent.com/63529720/79154962-ca484b00-7da6-11ea-8470-9953c83112a5.PNG)

This was tested with Kingdom of Scotland.

Map status:
![ScotlandIssue](https://user-images.githubusercontent.com/63529720/79155073-f6fc6280-7da6-11ea-801d-88fe38f2ba3f.PNG)

Database situation:

Kingdom is created
![DBKingdoms](https://user-images.githubusercontent.com/63529720/79155249-3cb92b00-7da7-11ea-8fd9-76a2202d64e9.PNG)

Capital Region is not properly assigned to Kingdom (assigned to 37 "Independant")
![DBregions](https://user-images.githubusercontent.com/63529720/79155302-49d61a00-7da7-11ea-8e42-bfbc4ced2457.PNG)

======================
List of broken Kingdoms.
![BrokenKingdoms](https://user-images.githubusercontent.com/63529720/79156789-e0a3d600-7da9-11ea-879a-ef480e8c4752.PNG)

**Comment by Enoc-GitHub** [comment]
**SOLUTION:**

_**Assign to Kingdom of Scotland:**_
UPDATE regions SET kingdom_id = '19' WHERE name = 'regions.lothian';


It takes a few seconds/minutes but at some point DB refreshes and changes are visible in the game.

![ScotlandIssuefix](https://user-images.githubusercontent.com/63529720/79160340-ffa56680-7daf-11ea-8099-43a260e96085.PNG)


_**SQL Statements to fix all Kingdoms:**_
UPDATE regions SET kingdom_id = '19' WHERE name = 'regions.lothian';
UPDATE regions SET kingdom_id = '28' WHERE name = 'regions.lisboa';
UPDATE regions SET kingdom_id = '18' WHERE name = 'regions.london';
UPDATE regions SET kingdom_id = '34' WHERE name = 'regions.sjaelland';
UPDATE regions SET kingdom_id = '39' WHERE name = 'regions.konigsberg';
UPDATE regions SET kingdom_id = '45' WHERE name = 'regions.bursa';
UPDATE regions SET kingdom_id = '25' WHERE name = 'regions.brugge';

**Comment by lothropgauss** [comment]
Fixed.
