### ISSUE TITLE
Undefined Regions / Broken Regions

### ISSUE THREAD

**Issue by Enoc-GitHub** [jeffreypicard/medieval-europe#16]
Issue found while checking the map.
![unasignedregions](https://user-images.githubusercontent.com/63529720/79157542-24e3a600-7dab-11ea-95fb-e809cd955cff.PNG)

Region names:
- Siena 
- Firenze

Issue found: Regions in DB belong to Kingdoms in status = deleted:
![deletedkingdomsregionissue](https://user-images.githubusercontent.com/63529720/79157675-65dbba80-7dab-11ea-84db-29bdca787c9d.PNG)

![deletedkingdomsregionissue2](https://user-images.githubusercontent.com/63529720/79157731-7f7d0200-7dab-11ea-8374-4f4d594488de.PNG)

Possible fix: Update DB tables assigning proper kingdom.

**Comment by Enoc-GitHub** [comment]
**SOLUTION**:

Must execute commands in the following order to be able to fix. If capital and kingdom_id fields are updated on the same SQL statement, it fails to properly update row.

_**Disable Capital Region:**_
UPDATE regions SET capital = '0' WHERE name = 'regions.siena';
UPDATE regions SET capital = '0' WHERE name = 'regions.firenze';

_**Assign to Independent Kingdom:**_
UPDATE regions SET kingdom_id = '37' WHERE name = 'regions.siena';
UPDATE regions SET kingdom_id = '37' WHERE name = 'regions.firenze';

It takes a few seconds/minutes but at some point DB refreshes and changes are visible in the game.
![unasignedregionsfix](https://user-images.githubusercontent.com/63529720/79159852-375fde80-7daf-11ea-88ff-56daac8e30b6.PNG)

**Comment by lothropgauss** [comment]
Fixed
