### ISSUE TITLE
Errors with Royal Palace - Level 1

### ISSUE THREAD

**Issue by Enoc-GitHub** [jeffreypicard/medieval-europe#17]
As King of the Kingdom, i went to the Royal Palace structure and clicked "Manage". 

**_This error was visible._**
![imagen](https://user-images.githubusercontent.com/63529720/79176797-98031180-7dd7-11ea-96e8-32521f02328b.png)

If one clicks on "Storage" or "Rest", one can access the Royal Palace. But buttons marked with red circles do not work.
![imagen](https://user-images.githubusercontent.com/63529720/79176906-dbf61680-7dd7-11ea-8a8f-d7bedd830aef.png)

**Logging showed no clear error:**
![imagen](https://user-images.githubusercontent.com/63529720/79176955-f9c37b80-7dd7-11ea-9d28-b728051ea68b.png)

Same tested on "Castle" and it works perfectly fine.

**Comment by lothropgauss** [comment]
I believe I found the issue and fixed it. It was related to the sql_mode which enforces stricter semantically correct sql queries in newer versions of mysql whereas older ones let you be sloppy and get away with it. 

My fix:
At the bottom of file /etc/mysql/mysql.conf.d/mysqld.cnf add the following.

sql_mode= "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

@Enoc-GitHub could you please check and confirm this is fixed? I'm not king in any kingdom so I can't access that menu atm :)

**Comment by KingKolSWE** [comment]
Once the fix is fully in place I will check.

**Comment by KingKolSWE** [comment]
Palace reviewed after the fix was put in place.  Not seeing this issue anymore.

**Comment by lothropgauss** [comment]
Great, closing this.
